from __future__ import annotations
import os
import tempfile
from pathlib import Path
from src.observability import get_logger
from src.validation.enriched.models import EnrichedTableMetrics

logger = get_logger(__name__)

def generate_markdown_report(
    run_id: str,
    timestamp: str,
    table_metrics: list[EnrichedTableMetrics],
    overall_status: str,
    output_path: Path,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    status_emoji = {"PASS": "✅", "WARN": "⚠️", "FAIL": "❌"}

    lines = [
        "# Enriched Silver Quality Report",
        "",
        f"**Last Updated:** {timestamp}",
        f"**Run ID:** `{run_id}`",
        f"**Overall Status:** {status_emoji.get(overall_status, '❓')} {overall_status}",
        "",
        "## Summary",
        "",
        "| Table | Partition | Value | Rows | Min Rows | Δ vs prior | Status | Notes |
        "|-------|-----------|-------|------|----------|-----------|--------|-------|",
    ]

    for metrics in table_metrics:
        notes = ", ".join(metrics.notes) if metrics.notes else "-"
        min_rows = metrics.min_rows if metrics.min_rows is not None else "-"
        delta_display = "-"
        if metrics.row_delta_pct is not None:
            delta_display = f"{metrics.row_delta_pct:+.2f}%"
        lines.append(
            f"| {metrics.table} | {metrics.partition_key} | {metrics.ingest_dt or '-'} | "
            f"{metrics.row_count:,} | {min_rows} | {delta_display} | "
            f"{status_emoji.get(metrics.status, '❓')} {metrics.status} | {notes} |"
        )

    failing = [m for m in table_metrics if m.status == "FAIL"]
    warning = [m for m in table_metrics if m.status == "WARN"]
    if failing or warning:
        lines.extend(["", "---", "", "## Issues Detected", ""])
        for metrics in failing + warning:
            emoji = status_emoji.get(metrics.status, "❓")
            lines.append(f"### {emoji} {metrics.table}")
            if metrics.ingest_dt:
                lines.append(
                    f"- **Partition:** {metrics.partition_key}={metrics.ingest_dt}"
                )
            lines.append(f"- **Rows:** {metrics.row_count:,}")
            if metrics.min_rows is not None:
                lines.append(f"- **Min Rows:** {metrics.min_rows}")
            if metrics.row_delta_pct is not None:
                lines.append(f"- **Row Delta vs prior:** {metrics.row_delta_pct:+.2f}%")
            if metrics.notes:
                lines.append(f"- **Notes:** {', '.join(metrics.notes)}")
            lines.append("")

    lines.extend(["---", "", "## Schema & Null Rates", ""])
    for metrics in table_metrics:
        lines.append(f"### {metrics.table}")
        if metrics.schema_snapshot:
            lines.append("")
            lines.append("**Schema (column → dtype):**")
            lines.append("")
            lines.append("| Column | Dtype |")
            lines.append("|--------|-------|")
            for col, dtype in metrics.schema_snapshot.items():
                lines.append(f"| {col} | {dtype} |")
        else:
            lines.append("")
            lines.append("- **Schema:** unavailable")
        if metrics.null_rates:
            lines.append("")
            lines.append("**Key Field Null Rates:**")
            lines.append("")
            lines.append("| Column | Null Rate |")
            lines.append("|--------|----------|")
            for col, rate in metrics.null_rates.items():
                lines.append(f"| {col} | {rate:.2%} |")
        else:
            lines.append("")
            lines.append("- **Key Field Null Rates:** unavailable")
        if metrics.sanity_issues:
            lines.append("")
            lines.append(f"**Sanity Issues:** {', '.join(metrics.sanity_issues)}")
        if metrics.semantic_issues:
            lines.append("")
            lines.append(f"**Semantic Issues:** {', '.join(metrics.semantic_issues)}")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "## Metadata",
            "",
            "- **Generated by:** `src/validation/enriched/report.py`",
            "- **Report Format Version:** 1.0",
            "",
            "<!-- AUTO-GENERATED - DO NOT EDIT MANUALLY -->",
        ]
    )

    content = "\n".join(lines)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        delete=False,
        dir=output_path.parent,
        prefix=f".{output_path.name}.",
        suffix=".tmp",
    ) as handle:
        handle.write(content)
        temp_name = handle.name

    os.replace(temp_name, output_path)
    logger.info(f"Wrote Markdown report to: {output_path}")
